---
title: "30_merge_teams"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}
pacman::p_load(tidyverse, furrr)
plan(multiprocess)
```


```{r}
load("data/team_data.Rdata")

tp <- team_data %>%
  mutate(oos = sample(1:3, n(), replace = T, c(.6, .2, .2))) %>%
  dplyr::select(
    label1 = local_team, 
    label2 = local_team_name, 
    oos
  ) %>% 
  dplyr::bind_rows(
    team_data %>%
      dplyr::select(
        label1 = visitor_team, 
        label2 = visitor_team_name, 
        oos
      ) 
  ) %>% 
  mutate(y = 1) %>% 
  unique %>%
  add_count(label1) %>%
  filter(n==1) %>%
  add_count(label2) %>%
  filter(n==1) %>%
  select(-n) 

tp %>% glimpse
```


```{r}
### Fake positives
character_modify <- function(x){
  
  # hinzufügen
  if(as.logical(rbinom(1, 1, .1))){
    
    ind <- sample(x = 1:3, size = 1, replace = T)
    
    if(ind == 1)  x <- paste(x, sample(letters, 1), collapse = "")
    if(ind == 2)  x <- ""
    if(ind == 3)  x <- " "
  }
  
  return(x)
}

transform_names <- function(x){
  x %>% purrr::map_chr(~.x %>% purrr::map(character_modify) %>% purrr::reduce(c) %>% paste(collapse = "")) 
}

transform_names_fast <- function(x){
  x %>% furrr::future_map_chr(~.x %>% purrr::map(character_modify) %>% purrr::reduce(c) %>% paste(collapse = ""), .progress = T) 
}
```

## Fake Positives

```{r}
tp_chars <- tp %>%
  mutate(
    label_1 = str_extract_all(label1, "."),
    label_2 = str_extract_all(label2, ".")
  )  %>%
  glimpse

ftp <- 1:1000 %>%
  furrr::future_map_dfr(~{
    bind_rows(
      tp_chars %>% mutate(label1 = label_1 %>% transform_names) %>% select(label1, label2, oos) %>% mutate(y = 1),
      tp_chars %>% mutate(label2 = label_2 %>% transform_names) %>% select(label1, label2, oos) %>% mutate(y = 1)
    )
  }, .progress = T)

ftp %>% glimpse
```


## Fake Negatives

```{r}
tp_rev <- tp %>% rename(labelX = label1) %>% rename(label1 = label2) %>% rename(label2 = labelX)

tn <- tp %>%
  split(.$oos) %>%
  imap_dfr(~{
    expand.grid(label1 = .x$label1, label2 = .x$label2) %>%
      dplyr::anti_join(tp, by = c("label1", "label2")) %>% 
      dplyr::anti_join(tp_rev, by = c("label1", "label2")) %>% 
      dplyr::mutate(y = 0, oos = as.numeric(.y))
  }) %>%
  glimpse

tn_chars <- tn %>%
  mutate(
    label_1 = str_extract_all(label1, "."),
    label_2 = str_extract_all(label2, ".")
  )  %>%
  glimpse


ftn <- 1:3 %>%
  map_dfr(~{
    bind_rows(
      tn_chars %>% mutate(label1 = label_1 %>% transform_names_fast) %>% select(label1, label2, oos) %>% mutate(y = 0),
      tn_chars %>% mutate(label2 = label_2 %>% transform_names_fast) %>% select(label1, label2, oos) %>% mutate(y = 0)
    )
  })

ftn %>% 
  glimpse
```


```{r}
sample_n_pos <- function(.x, k) {
  snp <- possibly(sample_n, .x)
  out <- snp(.x, k)
  if(is.null(out)) return(.x)
  return(out)
}

sample_group_n <- function(.x, param = c(400000, 20000, 20000)){
  
  out <- .x %>%
    split(.$oos) %>% 
    set_names(1:length(.)) %>%
    map2_dfr(param,~{
      num <- .y
      .x %>% 
        split(.$y) %>% 
        purrr::map_dfr(~{
          .x %>%
            distinct() %>%
            sample_n_pos(num)
        })
    })
  
  if(is.null(out)) return(.x)
  return(out)
}

syn_data <- list(ftp, ftn) %>%
  bind_rows() %>%
  sample_group_n() %>%
  bind_rows(
    bind_rows(tp, tn)
  ) %>%
  filter(!(oos == 1 & y == 0 & sample(c(F, T), size = n(), replace = T, prob = 
                                       c(.7, .3)))) %>%
  sample_n(n())
 

syn_data %>% 
  count(y, oos)

save(syn_data, file = "data/syn_data.Rdata")
```



